name: Build Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Multi-Arch Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout the code recursively, including submodules
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Clone submodules recursively

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    # Log in to DockerHub (optional if you want to push to a registry)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the multi-architecture Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/ansible-galaxy:latest
